version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cts_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cts_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: cts_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cts_celery
    command: celery -A cts_turismo_backend worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
